source_db:
  user: postgres
  password: pg123
  host: localhost
  port: 5432
  database: source_db

analytics_db:
  user: postgres
  password: pg123
  host: localhost
  port: 5432
  database: analytics_db
